### ISSUE TITLE
Problem with 1.0.0 version

### ISSUE THREAD

**Issue by Vivecstel** [loukwn/StageStepBar#5]
Seems like 'com.loukwn.stagestepbar_compose.data' is not added in the aar library or got obfuscated. Didn't have this issue with the previous library.

**Comment by loukwn** [comment]
Hey thanks for raising this! Some life stuff do not allow me to spend a lot of time on this rn so if you think you already know what is up then feel free to open a PR. I will look at it anyway asap.

**Comment by loukwn** [comment]
Also good spot. I think I need to properly add checks for release builds.

**Comment by loukwn** [comment]
@Vivecstel Sorry for taking too long but version 1.0.1 should be fine
